resources:
  - name: git_repo
    type: GitRepo
    configuration:
      gitProvider: mkGithub
      path: Manokarthi2412/yaml-validation
      branches:
        include: main
pipelines:
  - name: mvn_build
    steps:
      - name: mvn_build
        type: MvnBuild
        configuration:
          integrations:
            - name: mkartifactory
          inputResources:
            - name: git_repo
          mvnCommand: clean install -DskipTests # optional
